addSbtPlugin("org.tpolecat"      % "tut-plugin"   % "0.4.7")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"   % "0.3.3")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.3")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "1.1")
